//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Apartment
    {
        public Apartment()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Leases = new HashSet<Leas>();
            this.Brokers = new HashSet<Broker>();
        }
    

        public int ApartmentId { get; set; }

        [DisplayName("Building number")]
        public int ApartmentNumber { get; set; }
        public string StreetName { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> Floor { get; set; }
        public int NumberOfBedrooms { get; set; }
        public int NumberOfBathrooms { get; set; }
        public string Status { get; set; }

        [DisplayName("Apartment number")]
        public string Notes { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Leas> Leases { get; set; }
        public virtual ICollection<Broker> Brokers { get; set; }
    }
}
