//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public int CustomerId { get; set; }
        public int BrokerId { get; set; }
        public int ApartmentId { get; set; }

        //DateTime.Parse(DateTime.Now.ToShortDateString());
        public System.DateTime Date { get; set; }
       
        public string Time { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Broker Broker { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
