//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Broker
    {
        public Broker()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Leases = new HashSet<Leas>();
            this.Apartments = new HashSet<Apartment>();
            this.Customers = new HashSet<Customer>();
            this.Owners = new HashSet<Owner>();
        }
    
        public int BrokerId { get; set; }
        public string BrokerFirstName { get; set; }
        public string BrokerLastName { get; set; }

        [DisplayName("Username or Email")]
        [Required(ErrorMessage = "This field is required")]
      
       
        public string BrokerEmail { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string BrokerPassword { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Leas> Leases { get; set; }
        public virtual ICollection<Apartment> Apartments { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Owner> Owners { get; set; }
    }
}
