//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Leas
    {
        public Leas()
        {
            this.Tenants = new HashSet<Tenant>();
        }

        [DisplayName("# Lease")]
        public int LeaseId { get; set; }

        [DisplayName("Payment Date")]
        public string PaymentDate { get; set; }

        [DisplayName("# Broker")]
        public int BrokerId { get; set; }

        [DisplayName("# Owner")]
        public int OwnerId { get; set; }

        [DisplayName("Monthly rate")]
        public int MonthlyRate { get; set; }

        [DisplayName("Payment method")]
        public string PaymentMethod { get; set; }
        public Nullable<int> Fine { get; set; }

        [DisplayName("Start day")]
        public System.DateTime StartLeaseDate { get; set; }

        [DisplayName("Password")]
        public System.DateTime EndLeaseDate { get; set; }
        public int ApartmentId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Broker Broker { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
    }
}
