//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Owner
    {
        public Owner()
        {
            this.Leases = new HashSet<Leas>();
            this.Brokers = new HashSet<Broker>();
        }
    
        public int OwnerId { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }

        [DisplayName("Username or Email")]
        [Required(ErrorMessage = "This field is required")]
      
        public string OwnerEmail { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string OwnerPhoneNumber { get; set; }
    
        public virtual ICollection<Leas> Leases { get; set; }
        public virtual ICollection<Broker> Brokers { get; set; }
    }
}
