//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Tenant
    {

        public int TenantId { get; set; }
        public int LeaseId { get; set; }
        public string TenantFirstName { get; set; }
        public string TenantLastName { get; set; }

        [DisplayName("Username or Email")]
        [Required(ErrorMessage = "This field is required")]
       
        public string TenantEmail { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string TenantPhoneNumber { get; set; }
    
        public virtual Leas Leas { get; set; }
    }
}
